# config file version
apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  # <bool> enable/disable basic auth
  #basicAuth: true
  # <string> basic auth username
  #basicAuthUser: admin
  # <string> basic auth password
  #basicAuthPassword: foobar
  # <bool> mark as default datasource. Max one per org
  isDefault: true
  # <map> fields that will be converted to json and stored in json_data
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
  version: 1
  editable: true
